var indata = [
 { name: 'Residential PV System',
   info: {
       descr: {
           name: 'Description',
           dfile: 'tabcontents/pv_descr.html',
           data: 'Overall descr',
       },
       comp: {
           name: 'Competition',
           data: 'HHI: 123, blah',
       },
       ip: {
           name: 'Patents',
           data: 'blee patents',
       },
       value: {
           name: 'Value Share',
           data: 'ding dong dooly fraction value',
       }
   },
 },
 { name: 'Panel',
   parent: 'Residential PV System'
 },
 { name: 'Cell',
   parent: 'Panel'
 },
 { name: 'Frame',
   parent: 'Panel',
 },
 { name: 'Glass',
   parent: 'Panel',
 },
 { name: 'Inverter',
   parent: 'Residential PV System'
 },
 { name: 'Semiconductors',
   parent: 'Inverter',
 },
 { name: 'Printed Circuit Boards',
   parent: 'Inverter',
 },
 { name: 'Other Components',
   parent: 'Inverter',
 },
 { name: 'Assembly',
   parent: 'Inverter',
 },
 { name: 'Installation',
   parent: 'Residential PV System'
 },
 { name: 'Labor',
   parent: 'Installation',
 },
 { name: 'Permitting',
   parent: 'Installation',
 },
 { name: 'Interconnection',
   parent: 'Installation',
 },
 { name: 'Inspection',
   parent: 'Installation',
 },
 { name: 'Balance of System',
   parent: 'Residential PV System'
 },
 { name: 'Wire',
   parent: 'Balance of System',
 },
 { name: 'Conduit',
   parent: 'Balance of System',
 },
 { name: 'Racking',
   parent: 'Balance of System',
 },
 { name: 'Finance',
   parent: 'Residential PV System',
 },
];
