var indata = [

 // Residential PV
 { name: 'Solar - Residential PV',
   id: 'rpv',
   info: {
       descr: {
           name: 'Description',
           htfile: 'tabcontents/rpv_descr.html',
       },
       comp: {
           name: 'Competition',
           data: 'HHI: 123, blah',
       },
       ip: {
           name: 'Patents',
           jsfile: 'tabcontents/rpv_patents.json',
       },
       value: {
           name: 'Value Share',
           htfile: 'tabcontents/rpv_val.html',
       }
   },
 },
 { name: 'Technology',
   id: 'rpv_tech',
   parent: 'rpv',
   info: {
       descr: {
           name: 'Description',
           htfile: 'tabcontents/rpv_descr.html',
       },
       comp: {
           name: 'Competition',
           data: 'HHI: 123, blah',
       },
       ip: {
           name: 'Patents',
           data: 'blee patents',
       },
       value: {
           name: 'Foo Bar Value Share',
           htfile: 'tabcontents/example.html',
       }
   },
 },
 { name: 'Module',
   id: 'rpv_tech_module',
   parent: 'rpv_tech',
 },
 { name: 'Silicon',
   id: 'rpv_tech_module_si',
   parent: 'rpv_tech_module'
 },
 { name: 'Wafer',
   id: 'rpv_tech_module_wafer',
   parent: 'rpv_tech_module'
 },
 { name: 'Module',
   id: 'rpv_tech_module_module',
   parent: 'rpv_tech_module',
 },
 { name: 'Inverter',
   id: 'rpv_tech_inverter',
   parent: 'rpv_tech'
 },
 { name: 'Semiconductors',
   id: 'rpv_inverter_semiconductors',
   parent: 'rpv_tech_inverter',
 },
 { name: 'Printed Circuit Boards',
   id: 'rpv_techi_inverter_pcb',
   parent: 'rpv_tech_inverter',
 },
 { name: 'Other Components',
   id: 'rpv_tech_inverter_other',
   parent: 'rpv_tech_inverter',
 },
 { name: 'Assembly',
   id: 'rpv_tech_inverter_assembly',
   parent: 'rpv_tech_inverter',
 },
 { name: 'Installation',
   id: 'rpv_install',
   parent: 'rpv'
 },
 { name: 'Labor',
   id: 'rpv_install_labor',
   parent: 'rpv_install',
 },
 { name: 'Permitting',
   id: 'rpv_install_permitting',
   parent: 'rpv_install',
 },
 { name: 'Interconnection',
   id: 'rpv_install_connection',
   parent: 'rpv_install',
 },
 { name: 'Inspection',
   id: 'rpv_install_inspection',
   parent: 'rpv_install',
 },
 { name: 'Balance of System',
   id: 'rpv_bos',
   parent: 'rpv',
 },
 { name: 'Wire',
   id: 'rpv_bos_wire',
   parent: 'rpv_bos',
 },
 { name: 'Conduit',
   id: 'rpv_bos_conduit',
   parent: 'rpv_bos',
 },
 { name: 'Racking',
   id: 'rpv_bos_racking',
   parent: 'rpv_bos',
 },
 { name: 'Finance',
   id: 'rpv_finance',
   parent: 'rpv',
 },



 // Utility PV
 { name: 'Solar - Utility Scale PV',
   id: 'upv',
 },
 { name: 'Technology',
   id: 'upv_tech',
   parent: 'upv',
 },
 { name: 'Solar Module',
   id: 'upv_tech_module',
   parent: 'upv_tech',
 },
 { name: 'Silicon',
   id: 'upv_tech_module_si',
   parent: 'upv_tech_module',
 },
 { name: 'Wafers',
   id: 'upv_tech_module_wafer',
   parent: 'upv_tech_module',
 },
 { name: 'Cells',
   id: 'upv_tech_module_cell',
   parent: 'upv_tech_module',
 },
 { name: 'Module',
   id: 'upv_tech_module_module',
   parent: 'upv_tech_module',
 },
 { name: 'Inverter',
   id: 'upv_tech_inverter',
   parent: 'upv_tech',
 },
 { name: 'Project Development',
   id: 'upv_proj',
   parent: 'upv',
 },
 { name: 'Engineering',
   id: 'upv_proj_engineering',
   parent: 'upv_proj',
 },
 { name: 'Procurement',
   id: 'upv_proj_procurement',
   parent: 'upv_proj',
 },
 { name: 'Construction',
   id: 'upv_proj_construction',
   parent: 'upv_proj',
 },
 { name: 'Installation',
   id: 'upv_proj_construction_installation',
   parent: 'upv_proj_construction',
 },
 { name: 'Independent Power Producer',
   id: 'upv_ipp',
   parent: 'upv',
 },
 { name: 'Transmission & Distribution',
   id: 'upv_td',
   parent: 'upv',
 },
 { name: 'Utility / Transmission Owner',
   id: 'upv_td_util',
   parent: 'upv_td',
 },


 // Everything Wind
 { name: 'Wind Power',
   id: 'wp',
 },
 { name: 'Technology',
   id: 'wp_tech',
   parent: 'wp',
 },
 { name: 'Rotors / Blades',
   id: 'wp_tech_blades',
   parent: 'wp_tech',
 },
 { name: 'Drive Train',
   id: 'wp_tech_drivetrain',
   parent: 'wp_tech',
 },
 { name: 'Nacelle Module',
   id: 'wp_tech_nacelle',
   parent: 'wp_tech',
 },
 { name: 'Tower Module',
   id: 'wp_tech_tower',
   parent: 'wp_tech',
 },
 { name: 'Balance of System',
   id: 'wp_bos',
   parent: 'wp',
 },
 { name: 'Project Development',
   id: 'wp_project',
   parent: 'wp',
 },
 { name: 'Procurement',
   id: 'wp_procurement',
   parent: 'wp',
 },
 { name: 'Site Assessment',
   id: 'wp_procurement_site',
   parent: 'wp_procurement',
 },
 { name: 'Permitting',
   id: 'wp_procurement_permitting',
   parent: 'wp_procurement',
 },
 { name: 'Staging',
   id: 'wp_procurement_staging',
   parent: 'wp_procurement',
 },
 { name: 'Generator',
   id: 'wp_generator',
   parent: 'wp',
 },
 { name: 'Independent Power Producer',
   id: 'wp_generator_ipp',
   parent: 'wp_generator',
 },
 { name: 'Transmission and Distribution',
   id: 'wp_td',
   parent: 'wp',
 },
 { name: 'Utility',
   id: 'wp_td_utility',
   parent: 'wp_td',
 },

 // Everything Coal
 { name: 'Coal Plant',
   id: 'coal',
 },

];
